// Package generator emits type-safe Go camera bindings from a parsed GenICam XML
// description. Output is a single importable Go file ({PackageName}.go).
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"

	"github.com/aaronmurniadi/genicam-codegen/pkg/parser"
)

// Options controls code generation.
type Options struct {
	// PackageName is the Go package name for the generated code (default: "genicam").
	PackageName string
	// RuntimeImport is the import path of the runtime package (default: "github.com/aaronmurniadi/genicam-codegen/pkg/runtime").
	RuntimeImport string
	// Visibility filters which features are emitted ("Beginner", "Expert", "Guru").
	Visibility string
	// OutputFile overrides the generated filename (default: "{PackageName}.go").
	OutputFile string
}

func (o *Options) apply() error {
	if o.PackageName == "" {
		o.PackageName = "genicam"
	}
	if o.RuntimeImport == "" {
		o.RuntimeImport = "github.com/aaronmurniadi/genicam-codegen/pkg/runtime"
	}
	if o.OutputFile == "" {
		o.OutputFile = o.PackageName + ".go"
	}
	v, err := normalizeVisibility(o.Visibility)
	if err != nil {
		return err
	}
	o.Visibility = v
	return nil
}

// Files maps output filenames to formatted Go source.
type Files map[string][]byte

// Generate produces a single Go source file from a parsed RegisterDescription.
func Generate(rd *parser.RegisterDescription, opts Options) (Files, error) {
	if err := opts.apply(); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := writeHeader(&buf, rd, opts); err != nil {
		return nil, fmt.Errorf("header: %w", err)
	}
	writeImports(&buf, opts)
	writeEnums(&buf, rd, opts)
	if err := writeDevice(&buf, rd, opts); err != nil {
		return nil, fmt.Errorf("device: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w", err)
	}
	return Files{opts.OutputFile: formatted}, nil
}

// ──────────────────────────────────────────────────────────────────────────────
// file header
// ──────────────────────────────────────────────────────────────────────────────

var headerTmpl = template.Must(template.New("header").Parse(`// Code generated by genicam-codegen. DO NOT EDIT.
//
// Source: {{.VendorName}} {{.ModelName}} GenICam XML
//
// Usage:
//
//	import "your/module/pkg/runtime"
//	import cam "your/module/internal/camera"
//
//	nm, err := runtime.OpenGigeNodeMap(device, cameraIP)
//	cam := cam.New(nm)
//	cam.TriggerControl.TriggerSoftware()
package {{.Pkg}}
`))

type headerData struct {
	Pkg           string
	VendorName    string
	ModelName     string
	RuntimeImport string
}

func writeHeader(w *bytes.Buffer, rd *parser.RegisterDescription, opts Options) error {
	return headerTmpl.Execute(w, headerData{
		Pkg:           opts.PackageName,
		VendorName:    rd.VendorName,
		ModelName:     rd.ModelName,
		RuntimeImport: opts.RuntimeImport,
	})
}

func writeImports(w *bytes.Buffer, opts Options) {
	fmt.Fprintf(w, "\nimport (\n\t\"%s\"\n)\n\n", opts.RuntimeImport)
}

// ──────────────────────────────────────────────────────────────────────────────
// enums
// ──────────────────────────────────────────────────────────────────────────────

func writeEnums(w *bytes.Buffer, rd *parser.RegisterDescription, opts Options) {
	var enums []*parser.Node
	for _, n := range rd.Nodes {
		if n.Kind == parser.KindEnumeration && nodeVisible(n, opts) {
			enums = append(enums, n)
		}
	}
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })

	for _, n := range enums {
		typeName := n.GoName + "Type"
		fmt.Fprintf(w, "// %s represents the %q enumeration.\n", typeName, n.Name)
		if n.ToolTip != "" {
			fmt.Fprintf(w, "// %s\n", sanitizeComment(n.ToolTip))
		}
		fmt.Fprintf(w, "type %s int64\n\n", typeName)
		fmt.Fprintf(w, "const (\n")
		usedConstNames := make(map[string]struct{})
		for i, e := range n.EnumEntries {
			constName := n.GoName + e.GoName
			if _, exists := usedConstNames[constName]; exists {
				constName = fmt.Sprintf("%s_%d", constName, e.NumericValue)
			}
			usedConstNames[constName] = struct{}{}
			if i == 0 {
				fmt.Fprintf(w, "\t// %s = %d\n", constName, e.NumericValue)
				fmt.Fprintf(w, "\t%s %s = %d\n", constName, typeName, e.NumericValue)
			} else {
				fmt.Fprintf(w, "\t// %s = %d\n", constName, e.NumericValue)
				fmt.Fprintf(w, "\t%s = %d\n", constName, e.NumericValue)
			}
		}
		fmt.Fprintf(w, ")\n\n")

		fmt.Fprintf(w, "func (v %s) String() string {\n\tswitch v {\n", typeName)
		usedCaseValues := make(map[int64]struct{})
		for _, e := range n.EnumEntries {
			if _, exists := usedCaseValues[e.NumericValue]; exists {
				continue
			}
			usedCaseValues[e.NumericValue] = struct{}{}
			fmt.Fprintf(w, "\tcase %d:\n\t\treturn %q\n", e.NumericValue, e.Name)
		}
		fmt.Fprintf(w, "\tdefault:\n\t\treturn \"unknown\"\n\t}\n}\n\n")
	}
}

// ──────────────────────────────────────────────────────────────────────────────
// Device, category structs, feature methods
// ──────────────────────────────────────────────────────────────────────────────

func writeDevice(w *bytes.Buffer, rd *parser.RegisterDescription, opts Options) error {
	categories := visibleCategories(rd, opts)
	looseNodes := visibleNodesWithoutCategory(rd, categories, opts)

	fmt.Fprintf(w, "// Device is the generated type-safe entry point for the camera.\n")
	fmt.Fprintf(w, "// Instantiate it with New(dev).\n")
	fmt.Fprintf(w, "type Device struct {\n")
	fmt.Fprintf(w, "\tdev runtime.NodeMap\n")
	for _, cat := range categories {
		fmt.Fprintf(w, "\t// %s – %s\n", cat.GoName, sanitizeComment(cat.ToolTip))
		fmt.Fprintf(w, "\t%s *%sCategory\n", cat.GoName, cat.GoName)
	}
	if len(looseNodes) > 0 {
		fmt.Fprintf(w, "\t// Uncategorized – features not assigned to a named category.\n")
		fmt.Fprintf(w, "\tUncategorized *UncategorizedCategory\n")
	}
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// New creates a Device backed by the given NodeMap.\n")
	fmt.Fprintf(w, "func New(dev runtime.NodeMap) *Device {\n")
	fmt.Fprintf(w, "\td := &Device{dev: dev}\n")
	for _, cat := range categories {
		fmt.Fprintf(w, "\td.%s = &%sCategory{dev: dev}\n", cat.GoName, cat.GoName)
	}
	if len(looseNodes) > 0 {
		fmt.Fprintf(w, "\td.Uncategorized = &UncategorizedCategory{dev: dev}\n")
	}
	fmt.Fprintf(w, "\treturn d\n}\n\n")

	for _, cat := range categories {
		if err := genCategory(w, rd, cat, opts); err != nil {
			return err
		}
	}
	if len(looseNodes) > 0 {
		if err := genLooseNodes(w, rd, looseNodes, opts); err != nil {
			return err
		}
	}
	return nil
}

// genCategory emits the struct and all feature methods for one category.
func genCategory(w *bytes.Buffer, rd *parser.RegisterDescription, cat *parser.Node, opts Options) error {
	fmt.Fprintf(w, "// %sCategory provides access to %q features.\n", cat.GoName, cat.Name)
	if cat.ToolTip != "" {
		fmt.Fprintf(w, "// %s\n", sanitizeComment(cat.ToolTip))
	}
	fmt.Fprintf(w, "type %sCategory struct { dev runtime.NodeMap }\n\n", cat.GoName)

	seen := make(map[string]struct{})
	for _, childName := range cat.Children {
		child, ok := rd.Nodes[childName]
		if !ok {
			continue
		}
		if child.Kind == parser.KindCategory {
			continue
		}
		if !nodeVisible(child, opts) {
			continue
		}
		if _, dup := seen[child.GoName]; dup {
			continue
		}
		seen[child.GoName] = struct{}{}
		if err := genFeatureMethod(w, cat.GoName+"Category", child, opts); err != nil {
			return err
		}
	}
	return nil
}

func genLooseNodes(w *bytes.Buffer, rd *parser.RegisterDescription, nodes []*parser.Node, opts Options) error {
	fmt.Fprintf(w, "// UncategorizedCategory holds features not assigned to a named category.\n")
	fmt.Fprintf(w, "type UncategorizedCategory struct { dev runtime.NodeMap }\n\n")
	seen := make(map[string]struct{})
	for _, n := range nodes {
		if !nodeVisible(n, opts) {
			continue
		}
		if _, dup := seen[n.GoName]; dup {
			continue
		}
		seen[n.GoName] = struct{}{}
		if err := genFeatureMethod(w, "UncategorizedCategory", n, opts); err != nil {
			return err
		}
	}
	return nil
}

// genFeatureMethod emits the method(s) for a single feature node.
func genFeatureMethod(w *bytes.Buffer, receiver string, n *parser.Node, opts Options) error {
	switch n.Kind {
	case parser.KindCommand:
		emitCommand(w, receiver, n)
	case parser.KindInteger:
		emitInteger(w, receiver, n)
	case parser.KindFloat:
		emitFloat(w, receiver, n)
	case parser.KindBoolean:
		emitBoolean(w, receiver, n)
	case parser.KindEnumeration:
		emitEnumeration(w, receiver, n)
	case parser.KindString:
		emitString(w, receiver, n)
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────────
// Per-kind method emitters
// ──────────────────────────────────────────────────────────────────────────────

func emitCommand(w *bytes.Buffer, recv string, n *parser.Node) {
	doc := featureDoc(n)
	fmt.Fprintf(w, "%s// %s executes the %q command.\n", doc, n.GoName, n.Name)
	fmt.Fprintf(w, "func (c *%s) %s() error {\n", recv, n.GoName)
	fmt.Fprintf(w, "\treturn c.dev.ExecuteCommand(%q)\n", n.Name)
	fmt.Fprintf(w, "}\n\n")
}

func emitInteger(w *bytes.Buffer, recv string, n *parser.Node) {
	doc := featureDoc(n)
	canRead := n.AccessMode == parser.AccessRO || n.AccessMode == parser.AccessRW
	canWrite := n.AccessMode == parser.AccessWO || n.AccessMode == parser.AccessRW

	if canRead {
		fmt.Fprintf(w, "%s// Get%s returns the %q integer value.\n", doc, n.GoName, n.Name)
		if n.Unit != "" {
			fmt.Fprintf(w, "// Unit: %s\n", n.Unit)
		}
		fmt.Fprintf(w, "func (c *%s) Get%s() (int64, error) {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.GetInteger(%q)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
	if canWrite {
		fmt.Fprintf(w, "// Set%s sets the %q integer value.\n", n.GoName, n.Name)
		if n.Min != "" || n.Max != "" {
			fmt.Fprintf(w, "// Range: [%s, %s]", n.Min, n.Max)
			if n.Inc != "" {
				fmt.Fprintf(w, " step %s", n.Inc)
			}
			fmt.Fprintf(w, "\n")
		}
		fmt.Fprintf(w, "func (c *%s) Set%s(v int64) error {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.SetInteger(%q, v)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
}

func emitFloat(w *bytes.Buffer, recv string, n *parser.Node) {
	canRead := n.AccessMode == parser.AccessRO || n.AccessMode == parser.AccessRW
	canWrite := n.AccessMode == parser.AccessWO || n.AccessMode == parser.AccessRW

	if canRead {
		fmt.Fprintf(w, "// Get%s returns the %q float value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Get%s() (float64, error) {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.GetFloat(%q)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
	if canWrite {
		fmt.Fprintf(w, "// Set%s sets the %q float value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Set%s(v float64) error {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.SetFloat(%q, v)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
}

func emitBoolean(w *bytes.Buffer, recv string, n *parser.Node) {
	canRead := n.AccessMode == parser.AccessRO || n.AccessMode == parser.AccessRW
	canWrite := n.AccessMode == parser.AccessWO || n.AccessMode == parser.AccessRW

	if canRead {
		fmt.Fprintf(w, "// Get%s returns the %q boolean value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Get%s() (bool, error) {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.GetBoolean(%q)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
	if canWrite {
		fmt.Fprintf(w, "// Set%s sets the %q boolean value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Set%s(v bool) error {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.SetBoolean(%q, v)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
}

func emitEnumeration(w *bytes.Buffer, recv string, n *parser.Node) {
	typeName := n.GoName + "Type"
	canRead := n.AccessMode == parser.AccessRO || n.AccessMode == parser.AccessRW
	canWrite := n.AccessMode == parser.AccessWO || n.AccessMode == parser.AccessRW

	if canRead {
		fmt.Fprintf(w, "// Get%s returns the current %q enumeration value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Get%s() (%s, error) {\n", recv, n.GoName, typeName)
		fmt.Fprintf(w, "\tv, err := c.dev.GetEnumeration(%q)\n", n.Name)
		fmt.Fprintf(w, "\treturn %s(v), err\n", typeName)
		fmt.Fprintf(w, "}\n\n")
	}
	if canWrite {
		fmt.Fprintf(w, "// Set%s sets the %q enumeration value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Set%s(v %s) error {\n", recv, n.GoName, typeName)
		fmt.Fprintf(w, "\treturn c.dev.SetEnumeration(%q, int64(v))\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
}

func emitString(w *bytes.Buffer, recv string, n *parser.Node) {
	canRead := n.AccessMode == parser.AccessRO || n.AccessMode == parser.AccessRW
	canWrite := n.AccessMode == parser.AccessWO || n.AccessMode == parser.AccessRW

	if canRead {
		fmt.Fprintf(w, "// Get%s returns the %q string value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Get%s() (string, error) {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.GetString(%q)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
	if canWrite {
		fmt.Fprintf(w, "// Set%s sets the %q string value.\n", n.GoName, n.Name)
		fmt.Fprintf(w, "func (c *%s) Set%s(v string) error {\n", recv, n.GoName)
		fmt.Fprintf(w, "\treturn c.dev.SetString(%q, v)\n", n.Name)
		fmt.Fprintf(w, "}\n\n")
	}
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

func featureDoc(n *parser.Node) string {
	if n.ToolTip == "" && n.Description == "" {
		return ""
	}
	tip := n.ToolTip
	if tip == "" {
		tip = n.Description
	}
	return "// " + sanitizeComment(tip) + "\n"
}

func sanitizeComment(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	return s
}

// NormalizeVisibility parses and canonicalizes a visibility flag value.
func NormalizeVisibility(s string) (string, error) {
	return normalizeVisibility(s)
}

func normalizeVisibility(s string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "", "beginner":
		return "Beginner", nil
	case "expert":
		return "Expert", nil
	case "guru":
		return "Guru", nil
	default:
		return "", fmt.Errorf("invalid visibility %q: want beginner, expert, or guru", s)
	}
}

func visibilityRank(v parser.Visibility) int {
	switch v {
	case parser.VisiExpert:
		return 1
	case parser.VisiGuru:
		return 2
	case parser.VisiInvisible:
		return 99
	default:
		return 0
	}
}

func maxVisibilityRank(level string) int {
	switch level {
	case "Expert":
		return 1
	case "Guru":
		return 2
	default:
		return 0
	}
}

func nodeVisible(n *parser.Node, opts Options) bool {
	if n.Visibility == parser.VisiInvisible {
		return false
	}
	return visibilityRank(n.Visibility) <= maxVisibilityRank(opts.Visibility)
}

func visibleCategories(rd *parser.RegisterDescription, opts Options) []*parser.Node {
	var out []*parser.Node
	for _, cat := range collectCategories(rd) {
		if categoryHasVisibleChild(rd, cat, opts) {
			out = append(out, cat)
		}
	}
	return out
}

func categoryHasVisibleChild(rd *parser.RegisterDescription, cat *parser.Node, opts Options) bool {
	for _, childName := range cat.Children {
		child, ok := rd.Nodes[childName]
		if !ok || child.Kind == parser.KindCategory {
			continue
		}
		if nodeVisible(child, opts) {
			return true
		}
	}
	return false
}

func visibleNodesWithoutCategory(rd *parser.RegisterDescription, cats []*parser.Node, opts Options) []*parser.Node {
	var out []*parser.Node
	for _, n := range nodesWithoutCategory(rd, cats) {
		if nodeVisible(n, opts) {
			out = append(out, n)
		}
	}
	return out
}

func collectCategories(rd *parser.RegisterDescription) []*parser.Node {
	var out []*parser.Node
	for _, n := range rd.Nodes {
		if n.Kind == parser.KindCategory {
			out = append(out, n)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func nodesWithoutCategory(rd *parser.RegisterDescription, cats []*parser.Node) []*parser.Node {
	assigned := make(map[string]bool)
	for _, cat := range cats {
		for _, ch := range cat.Children {
			assigned[ch] = true
		}
		assigned[cat.Name] = true
	}
	var out []*parser.Node
	for _, n := range rd.Nodes {
		if !assigned[n.Name] && n.Kind != parser.KindCategory {
			out = append(out, n)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
